
package daryl.system.comun.enums;

public enum CanalAmq {
	
	CHNL_ARIMA_A, CHNL_ARIMA_A2, CHNL_ARIMA_A3,
	CHNL_ARIMA_B, CHNL_ARIMA_B2, CHNL_ARIMA_B3,
	CHNL_ARIMA_C, CHNL_ARIMA_C2, CHNL_ARIMA_C3,
	CHNL_ARIMA_D, CHNL_ARIMA_D2, CHNL_ARIMA_D3,
	CHNL_RNA,
	CHNL_ANN, CHNL_ANN_B, 
	CHNL_VARIANCE, CHNL_VARIANCE_2, CHNL_VARIANCE_3,
	CHNL_VARIANCE_B, CHNL_VARIANCE_B2, CHNL_VARIANCE_B3;
	
}
