package daryl.system.comun.enums;

public enum CanalAmq {
	//Los INV no se usan
	CHNL_ARIMA_A,
	CHNL_ARIMA_A_INV,
	CHNL_ARIMA_B,
	CHNL_ARIMA_B_INV,
	CHNL_ARIMA_C,
	CHNL_ARIMA_C_INV,
	CHNL_ARIMA_D,
	CHNL_ARIMA_D_INV,
	CHNL_RNA,
	CHNL_RNA_INV,
	CHNL_VARIANCE,
	CHNL_VARIANCE_INV,
	CHNL_ARIMA_D2, CHNL_ARIMA_D3,
	CHNL_ARIMA_C2, CHNL_ARIMA_C3,
	CHNL_ARIMA_B2, CHNL_ARIMA_B3,
	CHNL_ARIMA_A2, CHNL_ARIMA_A3;
	

	
	
}
