FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD ./target/control-historico-operaciones-1.0.4.jar control-historico-operaciones-1.0.4.jar
ENTRYPOINT ["java","-jar","/control-historico-operaciones-1.0.4.jar"]